# -*-python-*-
Import('*')

XSTools_dir = '../auto/XSTools'

if not win32:
	dir = XSTools_dir + '/unix'

	e = env.Copy()
	e.Append(CPPPATH = dir)
	e.Program('consoleui-test', [
		'consoleui-test.cpp',
		dir + '/consoleui.cpp'
	])

else:
	dir = XSTools_dir + '/utils'

	e = env.Copy()
	e.Append(CPPPATH = dir)
	e.Append(LIBS = ['wininet'])
	e.Program('http-reader-test', [
		'http-reader-test.cpp',
		dir + '/http-reader.cpp',
		dir + '/std-http-reader.cpp'
	])
