# This file was automatically generated by SWIG
package Tools;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Toolsc;
bootstrap Tools;
package Tools;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package Tools;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package Tools;

*CalcPath_init = *Toolsc::CalcPath_init;
*CalcPath_pathStep = *Toolsc::CalcPath_pathStep;
*CalcPath_destroy = *Toolsc::CalcPath_destroy;

# ------- VARIABLE STUBS --------

package Tools;

1;
