# This file was automatically generated by SWIG
package Tools;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package Tools;
bootstrap Tools;
package Tools;
@EXPORT = qw( );
1;
