Import('*')

gtk = env.Copy();
gtk.ParseConfig('pkg-config --cflags gtk+-2.0 libglade-2.0 gthread-2.0')
gtk['LINKFLAGS'] = "`pkg-config --libs gtk+-2.0 libglade-2.0 gthread-2.0`"
gtk['CPPPATH'] += ['../lib']
gtk['LIBPATH'] += ['../lib/static']

gtktool = gtk.Program('grftool-gtk', 'gtk.c',
	LIBS=['z', 'static-grf'])
Clean('grftool-gtk', ['grftool.glade.bak', 'grftool.gladep.bak'])
Default(gtktool)
