Import('*')

tools = env.Copy()
tools['LIBPATH'] = ['../lib/static', '../lib/zlib']
tools['CPPPATH'] = ['../lib']
tools['CPPDEFINES'] = ['GRF_STATIC', 'SPR_STATIC']
if WIN32:
	tools['LIBS'] = ['static-grf', 'grfzlib-static']
else:
	tools['LIBS'] = ['static-grf', 'z']


# Commandline grf utility
grftool = tools.Program('grftool', 'grftool.c')
Default(grftool)
env.Install(BINDIR, grftool)


# Commandline sprite utility
spritetool = tools.Program('spritetool', 'spritetool.c')
Default(spritetool)
env.Install(BINDIR, spritetool)

# Commandline grf extraction utility
gxtool = tools.Program('gxtool', 'gx/gx.c')
Default(gxtool)
env.Install(BINDIR, gxtool)
