Import('*')

SConscript([
	'pathfinding/SConscript',
	'translation/SConscript',
	'misc/SConscript',
])

libs = [
	'pathfinding',
	'translation',
	'misc'
]
deps = []
deps_path = []

if win32:
	SConscript(['win32/SConscript'])
else:
	SConscript(['unix/SConscript'])
	libs += ['unix']
	deps += [
		'readline',
		'termcap'
	]
	perlenv['LINKFLAGS'] += ['-pthread']
	deps_path += ['/usr/lib/termcap']


# We're linking C++ objects so force usage of g++
XSTools = perlenv.SharedLibrary('XSTools', [],
	LIBS = libs + deps,
	LIBPATH = libs + deps_path,
	CC = 'g++')

if not win32:
	# Perl expects XSTools.so, not libXSTools.so, so create symlink.
	perlenv.Command('XSTools.so', XSTools,
		[['ln', '-sf', 'libXSTools.so', 'XSTools.so']],
		chdir=1)

