#!/bin/sh
rm -rf archive
cp -dpR trunk archive
cd archive
find -name '.svn' | xargs rm -rf
cp ../openkore-config.php config.php
chmod 664 config.php
cd ..
tar -c archive | bzip2 --best > archive.tar.bz2
rm -rf archive
