// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Apr 11 20:28:45 2006

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef MAINFRAME_H
#define MAINFRAME_H


class MainFrame: public wxFrame {
public:
    // begin wxGlade: MainFrame::ids
    // end wxGlade

    MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: MainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: MainFrame::attributes
    wxStaticText* label_1;
    wxTextCtrl* fileInput;
    wxButton* browseButton;
    wxGauge* progress;
    wxButton* aboutButton;
    wxButton* extractButton;
    wxButton* cancelButton;
    // end wxGlade
}; // wxGlade: end class


#endif // MAINFRAME_H
