// -*- C++ -*- generated by wxGlade 0.4.1 on Tue Apr 11 17:24:10 2006

#include "mainframe.h"


MainFrame::MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxICONIZE|wxCAPTION|wxMINIMIZE|wxCLOSE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU)
{
    // begin wxGlade: MainFrame::MainFrame
    label_1 = new wxStaticText(this, -1, wxT("Select your RO client's .exe file:"));
    fileInput = new wxTextCtrl(this, -1, wxT(""));
    browseButton = new wxButton(this, -1, wxT(" ... "), wxDefaultPosition, wxDefaultSize, wxBU_EXACTFIT);
    progress = new wxGauge(this, -1, 100, wxDefaultPosition, wxDefaultSize, wxGA_HORIZONTAL|wxGA_SMOOTH);
    extractButton = new wxButton(this, -1, wxT("Extract"));
    cancelButton = new wxButton(this, -1, wxT("Cancel"));

    set_properties();
    do_layout();
    // end wxGlade
}


void MainFrame::set_properties()
{
    // begin wxGlade: MainFrame::set_properties
    SetTitle(wxT("OpenKore Packet Length Extractor"));
    fileInput->SetFocus();
    extractButton->SetDefault();
    // end wxGlade
}


void MainFrame::do_layout()
{
    // begin wxGlade: MainFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_2 = new wxBoxSizer(wxHORIZONTAL);
    sizer_1->Add(label_1, 0, wxLEFT|wxRIGHT|wxTOP|wxEXPAND, 8);
    sizer_2->Add(fileInput, 1, wxLEFT|wxTOP|wxBOTTOM|wxALIGN_CENTER_VERTICAL, 8);
    sizer_2->Add(browseButton, 0, wxALL|wxALIGN_CENTER_VERTICAL, 8);
    sizer_1->Add(sizer_2, 0, wxEXPAND, 0);
    sizer_1->Add(progress, 0, wxLEFT|wxRIGHT|wxBOTTOM|wxEXPAND|wxADJUST_MINSIZE, 8);
    sizer_3->Add(extractButton, 0, wxLEFT|wxTOP|wxBOTTOM, 8);
    sizer_3->Add(cancelButton, 0, wxALL, 8);
    sizer_1->Add(sizer_3, 0, wxALIGN_RIGHT, 0);
    SetAutoLayout(true);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    sizer_1->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}

