import os

Import('*')

sources = Split('''
	linehandler.cpp
	lineparser.cpp
	main.cpp
	mainframe.cpp
	packet-length-analyzer.cpp
	utils.cpp
	view.cpp
	worker-thread.cpp
''')

e = env.Copy()
e.ParseConfig('wx-config --cflags')

# ParseConfig can't handle absolute filenames for static libraries, bah.
config = os.popen('wx-config --libs', 'r')
e['LINKFLAGS'] += Split(' '.join(config.readlines()))
config.close()

e.Program('openkore-packet-length-extractor', sources)
