import os

Import('*')

sources = Split('''
	linehandler.cpp
	lineparser.cpp
	main.cpp
	mainframe.cpp
	packet-length-analyzer.cpp
	utils.cpp
	view.cpp
	worker-thread.cpp
''')

e = wxenv.Copy()
e.Append(CPPPATH = ['..'])
e.Append(LIBPATH = ['../wz'])
e.Append(LIBS = ['wz'])
e.Program('openkore-packet-length-extractor', sources)
