# -*-python-*-
Import('*')
import os.path;


############### Define sources ###############

# C/C++ source files
sources = []
# XS source files (input : output)
XS_sources = {}


### Pathfinding
sources += [
	'pathfinding/algorithm.cpp',
	'pathfinding/wrapper.cpp'
]
XS_sources['pathfinding/wrapper.xs'] = 'pathfinding/wrapper.cpp'

### Translation
sources += [
	'translation/filereader.cpp',
	'translation/translator.cpp',
	'translation/wrapper.cpp'
]
if win32:
	sources += ['translation/winfilereader.cpp']
else:
	sources += ['translation/unixfilereader.cpp']
XS_sources['translation/wrapper.xs'] = 'translation/wrapper.cpp'

### Unix
if not win32:
	sources += [
		'unix/unix.cpp',
		'unix/consoleui.cpp'
	]
	XS_sources['unix/unix.xs'] = 'unix/unix.cpp';
	perlenv.Depends('unix/unix.cpp', ['unix/consoleui-perl.xs', 'unix/consoleui.h'])

## Win32
if win32:
	sources += [
		'win32/utils.cpp',
		'win32/wrapper.c'
	]
	XS_sources['win32/wrapper.xs'] = 'win32/wrapper.c'

## Utils
sources += [
	'utils/http-reader.cpp',
	'utils/std-http-reader.cpp',
	'utils/mirror-http-reader.cpp',
	'utils/c-bindings/http-reader.cpp',
	'utils/perl/HttpReader.cpp'
]
XS_sources['utils/perl/HttpReader.xs'] = 'utils/perl/HttpReader.cpp'
if not win32:
	perlenv.ParseConfig('curl-config --cflags --libs')

### Misc
sources += [
	'misc/misc.c',
	'misc/fastutils.cpp'
]
XS_sources['misc/misc.xs'] = 'misc/misc.c'
XS_sources['misc/fastutils.xs'] = 'misc/fastutils.cpp'


###################################################

for input, output in XS_sources.iteritems():
	perlenv.XS(output, input)


############### XSTools ###############

# External library dependencies
deps = []
deps_path = []

if not win32:
	deps += ['readline']
	if have_ncurses:
		deps += ['ncurses']
	else:
		deps += ['termcap']
		deps_path += ['/usr/lib/termcap']
	if not darwin:
		deps += ['pthread']
		perlenv['LINKFLAGS'] += ['-pthread']
else:
	deps += ['winmm', 'wininet']

perlenv['LIBS'] += deps
perlenv['LIBPATH'] += deps_path

# We're linking C++ objects so force usage of g++
XSTools = perlenv.NativeDLL('XSTools', sources, CC = 'g++')

if not win32 and not darwin:
	# Perl expects XSTools.so, not libXSTools.so, so create symlink.
	perlenv.Command('XSTools.so', XSTools,
		[['ln', '-sf', 'libXSTools.so', 'XSTools.so']],
		chdir=1)


############### NetRedirect.dll ###############

if win32:
	sources = [
		'win32/netredirect.cpp',
		'win32/utils-netredirect.cpp'
	]
	libenv.NativeDLL('NetRedirect', sources,
		CC = 'g++',
		LIBS = ['ws2_32'])
