#
# checkLooter
# Author: Henrybk
#
# What this plugin does:
# This plugin extends the check_attackLooter hook and decides whether a monster
# should be considered a looter by reading its AI mode from monsters_table.txt.
# It is useful when attack logic or other automation wants to react differently
# to monsters that can pick up items.
#
# How it works:
# - When OpenKore runs the check_attackLooter hook, this plugin looks up the
#   target monster in %monstersTable.
# - It reads the monster Ai value from monsters_table.txt.
# - It converts that AI type into mode flags and checks whether the MD_LOOTER
#   bit is enabled.
# - If the monster is not a looter, the plugin sets $args->{return} = 1.
#
# How to configure it:
# This plugin does not require custom config.txt entries.
# Just enable the plugin and make sure your monsters_table.txt includes the Ai
# column generated by the converter.
#
# Examples:
# 1. Use this plugin together with attack systems that call check_attackLooter
#    so non-looter monsters can be filtered out automatically.
#
# 2. Keep this plugin enabled while using eCast if you want the old split
#    behavior where extended checks and looter checks are handled separately.
#
# Notes:
# - This plugin depends on monsters_table.txt having Ai data for each monster.
# - If a monster is missing from %monstersTable, the plugin logs a warning and
#   leaves the hook result unchanged.
#
package checkLooter;

use strict;
use Plugins;
use Globals;
use Log qw(debug warning);

use constant {
	PLUGIN_NAME => 'checkLooter',
};

Plugins::register(PLUGIN_NAME, 'Checks looter monsters using monsters_table.txt', \&onUnload);

my $hooks = Plugins::addHooks(
	['check_attackLooter', \&oncheck_attackLooter, undef],
);

my %ai_constant = (
	'01' => 0x81, '02' => 0x83, '03' => 0x1089, '04' => 0x3885,
	'05' => 0x2085, '06' => 0, '07' => 0x108B, '08' => 0x7085,
	'09' => 0x3095, '10' => 0x84, '11' => 0x84, '12' => 0x2085,
	'13' => 0x308D, '17' => 0x91, '19' => 0x3095, '20' => 0x3295,
	'21' => 0x3695, '24' => 0xA1, '25' => 0x1, '26' => 0xB695,
	'27' => 0x8084, 'ABR_PASSIVE' => 0x21, 'ABR_OFFENSIVE' => 0xA5
);

=pod
/// Monster mode definitions to clear up code reading. [Skotlex]
enum e_mode {
	MD_NONE					= 0x0000000,
	MD_CANMOVE				= 0x0000001,
	MD_LOOTER				= 0x0000002,
	MD_AGGRESSIVE			= 0x0000004,
	MD_ASSIST				= 0x0000008,
	MD_CASTSENSORIDLE		= 0x0000010,
	MD_NORANDOMWALK			= 0x0000020,
	MD_NOCAST				= 0x0000040,
	MD_CANATTACK			= 0x0000080,
	//FREE					= 0x0000100,
	MD_CASTSENSORCHASE		= 0x0000200,
	MD_CHANGECHASE			= 0x0000400,
	MD_ANGRY				= 0x0000800,
	MD_CHANGETARGETMELEE	= 0x0001000,
	MD_CHANGETARGETCHASE	= 0x0002000,
	MD_TARGETWEAK			= 0x0004000,
	MD_RANDOMTARGET			= 0x0008000,
	MD_IGNOREMELEE			= 0x0010000,
	MD_IGNOREMAGIC			= 0x0020000,
	MD_IGNORERANGED			= 0x0040000,
	MD_MVP					= 0x0080000,
	MD_IGNOREMISC			= 0x0100000,
	MD_KNOCKBACKIMMUNE		= 0x0200000,
	MD_TELEPORTBLOCK		= 0x0400000,
	//FREE					= 0x0800000,
	MD_FIXEDITEMDROP		= 0x1000000,
	MD_DETECTOR				= 0x2000000,
	MD_STATUSIMMUNE			= 0x4000000,
	MD_SKILLIMMUNE			= 0x8000000,
};
=cut

sub onUnload {
	Plugins::delHooks($hooks);
}

sub oncheck_attackLooter {
	my ($hook, $args) = @_;
	return 0 if (!$args->{monster} || $args->{monster}->{nameID} eq '');

	if (!exists $monstersTable{$args->{monster}->{nameID}}) {
		warning "[checkLooter] Monster {name '$args->{monster}->{name}'} {ID '$args->{monster}->{nameID}'} not found\n", 'checkLooter';
		return;
	}

	my $mob = $monstersTable{$args->{monster}->{nameID}};
	my $ai = $mob->{Ai};
	my $is_looter = is_monster_ai_looter($ai);
	if (!$is_looter) {
		debug "[checkLooter] [False] $args->{monster} ($args->{monster}->{nameID}) is not a Looter\n", 'checkLooter';
		$args->{return} = 1;
	} else {
		debug "[checkLooter] [True] $args->{monster} ($args->{monster}->{nameID}) is a Looter\n", 'checkLooter';
	}
}

sub is_monster_ai_looter {
	my ($ai_str) = @_;
	$ai_str = uc($ai_str);

	my $mode_value = exists $ai_constant{$ai_str}
		? $ai_constant{$ai_str}
		: $ai_constant{'06'};

	return ($mode_value & 0x2) ? 1 : 0;
}

1;
