name: Translation update

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GIT checkout
    - uses: actions/checkout@v4

    - name: Run update
      run: |
        cd src/po/
         ./update.sh
