name: Validate Python e2e
on:
  push:

jobs:
  default-version:
    name: Setup default version
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup default python
      uses: actions/setup-python@v2

    - name: Validate version
      run: python --version

    - name: Run simple python code
      run: python -c 'import math; print(math.factorial(5))'

  setup-versions-from-manifest:
    name: Setup ${{ matrix.python }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04, ubuntu-20.04]
        python: [2.7.18, 3.8.1]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    - name: Validate version
      run: |
        $pythonVersion = (python --version)
        $pythonVersion
      shell: pwsh

    - name: Run simple code
      run: python -c 'import math; print(math.factorial(5))'

  setup-pre-release-version-from-manifest:
    name: Setup 3.9.0-beta.4 ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python 3.9.0-beta.4
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.0-beta.4'

    - name: Validate version
      run: |
        $pythonVersion = (python --version)
        if ("Python 3.9.0b4" -ne "$pythonVersion"){
          Write-Host "The current version is $pythonVersion; expected version is 3.9.0b4"
          exit 1
        }
        $pythonVersion
      shell: pwsh

    - name: Run simple code
      run: python -c 'import math; print(math.factorial(5))'
