# runs-on:            https://github.com/actions/virtual-environments
# setup-python:       https://github.com/actions/setup-python
# actions-setup-perl: https://github.com/marketplace/actions/setup-perl-environment

name: make test

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  make_test:

    name: make test ${{ matrix.os }} (python ${{ matrix.python }}) (perl ${{ matrix.perl }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        #- os: windows-2016
        #  python: 2.7
        #  architecture: x86
        #  perl: 5.12
        #  distribution: default

        #- os: windows-latest
        #  python: 3
        #  architecture: x86
        #  perl: latest
        #  distribution: strawberry

        - os: ubuntu-18.04
          python: 2.7
          architecture: x64
          perl: 5.12
          distribution: default

        - os: ubuntu-latest
          python: 3
          architecture: x64
          perl: latest
          distribution: default

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # setup Windows matrix: python 2.7_x86, 3_x86 and perl 5.12_x64, strawberry last_x64
    # setup Linux   matrix: python 2.7_x64, 3_x64 and perl 5.12_x64, last_x64
    - name: setup-python ${{ matrix.python }} ${{ matrix.architecture }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: ${{ matrix.architecture }}

    - name: setup-perl ${{ matrix.perl }} (${{ matrix.distribution }})
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}
        distribution: ${{ matrix.distribution }}

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y libreadline6-dev libcurl4-openssl-dev

    - name: Environment check
      run: |
        echo "------------- check g++ version -------------"
        g++ --version
        echo "------------- perl version -------------"
        perl --version
        echo "------------- Time::HiRes module -------------"
        perl -e "use Time::HiRes;"
        echo "------------- Compress::Zlib module -------------"
        perl -e "use Compress::Zlib;"
        echo "------------- python version -------------"
        python -V

    - name: Run Tests
      run: make test
