name: CI Windows
on:
  push:
#    branches:
#      - master
#    tags-ignore:
#      - '*'
#  pull_request:

jobs:
  build_XSTools:

    name: Setup ${{ matrix.os }} (python ${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
#      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-18.04]
        python: [2.7, 3]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: setup-python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: 'x64'
#    - name: Install dependencies
#      run: |
#        echo Hello, world!
#        sudo apt update
#        sudo apt install -y libreadline6-dev libcurl4-openssl-dev python

    - name: Environment check
      run: |
        echo "------------- check g++ version -------------"
        g++ -v
        echo "------------- perl version -------------"
        perl -V
        echo "------------- Time::HiRes module -------------"
        perl -e "use Time::HiRes;"
        echo "------------- Compress::Zlib module -------------"
        perl -e "use Compress::Zlib;"
        echo "------------- python version -------------"
        python -V
#        python2 -V
    - name: Run make XSTools.dll
      run: |
        echo python2 src\scons-local-3.0.1\scons.py
#        echo "------------- make test -------------"
#        dir
#        make test