Import('*')

gtk = env.Copy();
gtk.ParseConfig('pkg-config --cflags gtk+-2.0 libglade-2.0 gthread-2.0')
gtk['LINKFLAGS'] = "`pkg-config --libs gtk+-2.0 libglade-2.0 gthread-2.0`"
gtk['CPPPATH'] += ['../lib']
gtk['LIBPATH'] += ['../lib/static']

CSourceBuilder = Builder(action = "gdk-pixbuf-csource --name=grftool_icon $SOURCE > $TARGET")
gtk.Append(BUILDERS = {'CSource' : CSourceBuilder});
Default(gtk.CSource('grftool-gtk.csource', 'grftool-gtk.png'))

gtktool = gtk.Program('grftool-gtk', ['main.cpp', 'callbacks.cpp', 'utils.cpp', 'window.cpp', 'sprite-viewer.cpp'],
	LIBS=['z', 'static-grf'])
Clean('grftool-gtk', ['grftool.glade.bak', 'grftool.gladep.bak'])
Default(gtktool)

env.Install(BINDIR, gtktool)
env.Install(DATADIR + '/applications', 'grftool-gtk.desktop')
env.Install(PKGDATADIR, 'grftool.glade')
